cc_library(
    name = "monolith",
    hdrs = ["monolith.h"],
    visibility = ["//c-toxcore/auto_tests:__pkg__"],
    deps = [
        "//c-toxcore/toxav:monolith",
        "//c-toxcore/toxcore:monolith",
        "//c-toxcore/toxencryptsave:monolith",
    ],
)
