#include "../toxcore/tox.c"

#include "../toxcore/DHT.c"
#include "../toxcore/LAN_discovery.c"
#include "../toxcore/Messenger.c"
#include "../toxcore/TCP_client.c"
#include "../toxcore/TCP_connection.c"
#include "../toxcore/TCP_server.c"
#include "../toxcore/crypto_core.c"
#include "../toxcore/crypto_core_mem.c"
#include "../toxcore/friend_connection.c"
#include "../toxcore/friend_requests.c"
#include "../toxcore/group.c"
#include "../toxcore/list.c"
#include "../toxcore/logger.c"
#include "../toxcore/network.c"
#include "../toxcore/net_crypto.c"
#include "../toxcore/onion.c"
#include "../toxcore/onion_announce.c"
#include "../toxcore/onion_client.c"
#include "../toxcore/ping.c"
#include "../toxcore/ping_array.c"
#include "../toxcore/tox_api.c"
#include "../toxcore/util.c"

#include "../toxav/audio.c"
#include "../toxav/bwcontroller.c"
#include "../toxav/groupav.c"
#include "../toxav/msi.c"
#include "../toxav/ring_buffer.c"
#include "../toxav/rtp.c"
#include "../toxav/toxav.c"
#include "../toxav/toxav_old.c"
#include "../toxav/video.c"

#include "../toxencryptsave/toxencryptsave.c"
