#!/bin/bash

set -eu

NPROC=$(nproc)

. ".github/scripts/flags-$CC.sh"

add_ld_flag -Wl,-z,defs

# Make compilation error on a warning
add_flag -Werror

add_config_flag --disable-ipv6
add_config_flag --enable-daemon
add_config_flag --with-log-level=TRACE

autoreconf -fi
mkdir -p _build
cd _build # pushd
../configure "${CONFIG_FLAGS[@]}" || (cat config.log && false)
make "-j$NPROC" -k CFLAGS="$C_FLAGS" LDFLAGS="$LD_FLAGS"
make -j50 -k distcheck DISTCHECK_CONFIGURE_FLAGS="${CONFIG_FLAGS[*]}" || (cat tox-*/_build/build/test-suite.log && false)
cd - # popd
