---
cirrus-ci_task:
  container:
    image: cirrusci/bazel:latest
    cpu: 8
    memory: 12G
  configure_script:
    - sudo apt update
    - sudo apt install -y
        autopoint
        libasound2-dev
        libcv-dev
        libhighgui-dev
        libopenal-dev
    - echo "build --jobs=50 --curses=no --verbose_failures" | sudo tee /etc/bazel.bazelrc
    - echo "build --config=linux" | sudo tee -a /etc/bazel.bazelrc
    - echo "build --config=gcc" | sudo tee -a /etc/bazel.bazelrc
    - echo "build --config=remote" | sudo tee -a /etc/bazel.bazelrc
    - cd .. && mv cirrus-ci-build c-toxcore
    - git clone --depth=1 https://github.com/TokTok/toktok-stack cirrus-ci-build
    - mv c-toxcore cirrus-ci-build
    - cd -
  test_all_script:
    - bazel test -c opt -k //c-toxcore/...
