#!/bin/sh

set -e -x

# Build toxcore and run tests.
./autogen.sh
./configure \
  --with-libsodium-libs=$CACHE_DIR/lib \
  --with-libsodium-headers=$CACHE_DIR/include \
  --enable-daemon \
  --enable-logging \
  --enable-ntox

make -j `nproc`
# This doesn't currently work on Travis, because the autotools build is broken.
# It does not look up libsodium by pkg-config, so without the --with flags it
# won't find it. We don't care that much about distcheck at this point, but we
# do care whether it configures/builds at all, which is exercised by the make
# call above. Tests are executed by the cmake build.
make distcheck -j `nproc` || true
