Document: tox
Title: Debian tox Manual
Author: <insert document author here>
Abstract: This manual describes what tox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tox/tox.sgml.gz

Format: postscript
Files: /usr/share/doc/tox/tox.ps.gz

Format: text
Files: /usr/share/doc/tox/tox.text.gz

Format: HTML
Index: /usr/share/doc/tox/html/index.html
Files: /usr/share/doc/tox/html/*.html
