#!/bin/sh

ACTION="$1"

set -eu

. other/travis/env.sh
. other/travis/env-freebsd.sh

travis_install() {
  . other/travis/freebsd-install
  . other/travis/freebsd-install-stage2
}

travis_script() {
  . other/travis/toxcore-script
}

if [ "-z" "$ACTION" ]; then
  "travis_script"
else
  "travis_$ACTION"
fi
