#!/bin/bash

# We only submit coverage from the Linux build.
coveralls               \
  --exclude auto_tests  \
  --exclude other       \
  --exclude testing     \
  --gcov-options '\-lp'

bash <(curl -s https://codecov.io/bash)
