#!/bin/sh

. other/analysis/gen-file.sh

put auto_tests/lan_discovery_test.c

# TODO(iphydf): Get rid of all VLAs, then enable -fstack-protector -Wstack-protector
gcc -O3 -c -o /dev/null test.c $CPPFLAGS	\
	-std=c99				\
	-pedantic				\
	-Wall					\
	-Wextra					\
	-Wno-aggregate-return			\
	-Wno-aggressive-loop-optimizations	\
	-Wno-float-conversion			\
	-Wno-format-signedness			\
	-Wno-missing-field-initializers		\
	-Wno-padded				\
	-Wno-sign-compare			\
	-Wno-sign-conversion			\
	-Wno-switch-default			\
	-Wno-unused-parameter			\
	-Wstrict-aliasing=0			\
	-Wstrict-overflow=1			\
        					\
	-Wbad-function-cast			\
	-Wmissing-declarations			\
	-Wmissing-parameter-type		\
	-Wmissing-prototypes			\
	-Wnested-externs 			\
	-Wold-style-declaration			\
	-Wold-style-definition			\
	-Wstrict-prototypes			\
	-Wbool-compare				\
	-Wc99-c11-compat			\
	-Wc++-compat				\
	-Wcast-align				\
	-Wcast-qual				\
	-Wchar-subscripts			\
	-Wdouble-promotion			\
	-Wduplicated-cond			\
	-Wempty-body				\
	-Wenum-compare				\
	-Wfloat-equal				\
	-Wformat=2				\
	-Wframe-address				\
	-Wframe-larger-than=133168		\
	-Wjump-misses-init			\
	-Wignored-qualifiers			\
	-Wignored-attributes			\
	-Wincompatible-pointer-types		\
	-Winit-self				\
	-Winline				\
	-Wlarger-than=133120			\
	-Wmaybe-uninitialized			\
	-Wmemset-transposed-args		\
	-Wmisleading-indentation		\
	-Wnonnull				\
	-Wnonnull-compare			\
	-Wnull-dereference			\
	-Wodr					\
	-Wredundant-decls			\
	-Wreturn-type				\
	-Wshadow				\
	-Wsuggest-attribute=format		\
	-Wundef					\
	-Wunsafe-loop-optimizations		\
	-Wunused-label				\
	-Wunused-local-typedefs			\
	-Wunused-value				\
	-Wunused-but-set-parameter		\
	-Wunused-but-set-variable		\
