#!/bin/bash

. other/analysis/gen-file.sh

set -e

run() {
  echo "Running Clang compiler in variant '$*'"
  clang++ -o /dev/null amalgamation.cc \
    "${CPPFLAGS[@]}" \
    "${LDFLAGS[@]}" \
    "$@" \
    -std=c++17 \
    -Werror \
    -Weverything \
    -Wno-alloca \
    -Wno-c++98-compat-pedantic \
    -Wno-c99-extensions \
    -Wno-conversion \
    -Wno-covered-switch-default \
    -Wno-disabled-macro-expansion \
    -Wno-documentation-deprecated-sync \
    -Wno-documentation-unknown-command \
    -Wno-global-constructors \
    -Wno-missing-braces \
    -Wno-missing-field-initializers \
    -Wno-missing-noreturn \
    -Wno-old-style-cast \
    -Wno-padded \
    -Wno-sign-compare \
    -Wno-tautological-pointer-compare \
    -Wno-unreachable-code-return \
    -Wno-unused-parameter \
    -Wno-used-but-marked-unused \
    -Wno-source-uses-openmp
}

. other/analysis/variants.sh
