# Find LIBCONFIG
#
# LIBCONFIG_INCLUDE_DIR
# LIBCONFIG_LIBRARY
# LIBCONFIG_FOUND
#

if (UNIX)
  find_package(PkgConfig QUIET)
  pkg_check_modules(_LIBCONFIG QUIET libconfig)
endif ()

FIND_PATH(LIBCONFIG_INCLUDE_DIR NAMES libconfig.h HINTS ${_LIBCONFIG_INCLUDEDIR})

FIND_LIBRARY(LIBCONFIG_LIBRARY NAMES config)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBCONFIG DEFAULT_MSG LIBCONFIG_LIBRARY LIBCONFIG_INCLUDE_DIR)

MARK_AS_ADVANCED(LIBCONFIG_INCLUDE_DIR LIBCONFIG_LIBRARY)
