# Find SODIUM
#
# SODIUM_INCLUDE_DIR
# SODIUM_LIBRARY
# SODIUM_FOUND
#

FIND_PATH(SODIUM_INCLUDE_DIR NAMES sodium.h)

FIND_LIBRARY(SODIUM_LIBRARY NAMES sodium)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SODIUM DEFAULT_MSG SODIUM_LIBRARY SODIUM_INCLUDE_DIR)

MARK_AS_ADVANCED(SODIUM_INCLUDE_DIR SODIUM_LIBRARY)
